library = library or _G.library or loadstring(game:HttpGet("http://zerotwohub.tk/uilibtest"))()
local window = library:CreateWindow("ZeroTwo Hub")
local main = window:CreateFolder("Main")

local lp = game.Players.LocalPlayer

function tp(part)
  if(type(part) == "table") then
    for i,v in pairs(part) do
      tp(v)
    end
  else
    pcall(function()
      part = part.CFrame
    end)
    lp.Character.HumanoidRootPart.CFrame = part
    wait(0.5)
  end
end

main:Toggle2("Auto Fish",function()
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.ToggleCastSound:FireServer(true)
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.CastFishingLine:FireServer()
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.ToggleCastSound:FireServer(false)
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.PlaySplashEffect:FireServer()
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.ToggleReelingSound:FireServer(true)
  spawn(function()
    game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.FishBiting:InvokeServer()
  end)
  wait(0.5)
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.FishCaught:FireServer()
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.ToggleReelingSound:FireServer(false)
  game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.ToggleCastSound:FireServer(false)
  wait(1.5)
end)

main:Toggle2("Auto Sell Fishes(slow)",function(self)
  for i,v in pairs(lp.PlayerGui.Interface.Inventory.Inventory.Frame.Backpack.List.Container:GetChildren()) do
    if(v:FindFirstChild("DraggableComponent")) then
      if(string.find(v.Name,"key_") and self:IsOn() and v.DraggableComponent.Contents.ItemViewport.Model:FindFirstChildOfClass("Tool").Name ~= "whalekey") then
        local args = {
            [1] = "SellAll",
            [2] = "SeaCreatureDrops",
            [3] = v.Name
        }
        game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.processGameItemSold:InvokeServer(unpack(args))
        args[2]="Fish"
        game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.processGameItemSold:InvokeServer(unpack(args))
      end
    end
  end
  wait(2)
end)

main:Toggle2("Sell everything(fast)",function()
    game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.processGameItemSold:InvokeServer("SellEverything")
    wait(2)
end)

main:Toggle2("Auto Kill Animals",function(self)
  for i,v in pairs(game.Workspace:GetChildren()) do
    if(v:FindFirstChild("Health") and v.Health:IsA("NumberValue") and v.Health.Value > 0 and self:IsOn() and v.Name ~= "MobyWood") then
      local args = {
          [1] = v, --attacked animal
          [2] = lp.Character:FindFirstChildOfClass("Tool").Name or "sharktooth", --used weapon
          [3] = true --prob if attack hit
      }
      repeat
        lp.Character.HumanoidRootPart.CFrame = v.HumanoidRootPart.CFrame*CFrame.new(0,0,30)
        game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.MonsterHit:FireServer(unpack(args))
        wait()
      until v == nil or v.Parent == nil or v:FindFirstChild("Health") == nil or v.Health.Value <= 0 or not self:IsOn()
    end
  end
end)

main:Toggle2("Auto Pickup",function()
  for i,v in pairs(game:GetService("Workspace").DroppedItems:GetChildren()) do
    if(v:FindFirstChild("Handle")) then
      tp(v.Handle)
    end
  end
end)

main:Toggle2("Auto open chests",function(self)
  for i,v in pairs(game.Workspace:GetChildren()) do
    if(string.find(v.Name,"ShipModel") or v.Name == "RandomChests") then
      for j,k in pairs(v:GetChildren()) do
        if(string.find(k.Name,"Chest_")) then
          tp(k.HumanoidRootPart)
          fireproximityprompt(k.HumanoidRootPart.ProximityPrompt)
        end
      end
    end
  end
end)

main:Toggle2("Auto Kill Moby Wood",function()
  if(game.Workspace:FindFirstChild("MobyWood")) then
    v = game.Workspace:FindFirstChild("MobyWood")
    if(v:FindFirstChild("Health") and v.Health:IsA("NumberValue") and v.Health.Value > 0) then
      local args = {
          [1] = v, --attacked animal
          [2] = lp.Character:FindFirstChildOfClass("Tool").Name or "sharktooth", --used weapon
          [3] = true --prob if attack hit
      }
      repeat
        lp.Character.HumanoidRootPart.CFrame = v.HumanoidRootPart.CFrame*CFrame.new(0,0,30)
        game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.MonsterHit:FireServer(unpack(args))
        wait()
      until v == nil or v.Parent == nil or v:FindFirstChild("Health") == nil or v.Health.Value <= 0 or not self:IsOn()
    end
  end
end)

--[[

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 1,
    [2] = 0
}

game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.ClaimDailyReward:InvokeServer(unpack(args))


]]


--[[

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "MrRodney"
}

game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.TutorialEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 4
}

game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.TutorialEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 6
}

game:GetService("ReplicatedStorage").CloudFrameShared.DataStreams.TutorialEvent:FireServer(unpack(args))





]]
