library = library or _G.library or loadstring(game:HttpGet("http://zerotwohub.tk/uilibtest"))()
local window = library:CreateWindow("ZeroTwo Hub")
local main = window:CreateFolder("Main")

local lp = game.Players.LocalPlayer

if(lp.Name == "Laugeyt") then repeat wait() until nil end

function touch(part)
  if(type(part) == "table") then
    for i,v in pairs(part) do
      touch(v)
      game:GetService("RunService").RenderStepped:Wait()
    end
  else
    if(part:IsA("BasePart")) then
      if(part.Transparency ~= 1 and part:FindFirstChildOfClass("TouchTransmitter")) then
        firetouchinterest(part,lp.Character.HumanoidRootPart,0)
        game:GetService("RunService").Stepped:Wait()
        firetouchinterest(part,lp.Character.HumanoidRootPart,1)
      end
    end
    if(part:IsA("Folder") or part:IsA("Model")) then
      touch(part:GetChildren())
    end
  end
  return true
end

function tp(part)
  if(type(part) == "table") then
    for i,v in pairs(part) do
      tp(v)
    end
  else
    lp.Character.HumanoidRootPart.CFrame = part
    wait(0.5)
  end
end

main:Toggle2("Auto Cook",function()
  if(lp.Character:FindFirstChildOfClass("Tool")==nil) then
    local args = {
        [1] = "EquipTool",
        [2] = {
            [1] = true,
            [2] = lp.PlayerGui.ToolBar.Bar.Slot1.Item.Value
        }
    }
    print("equip Tool")
    game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
  end
  for i,v in ipairs(game:GetService("Workspace").Players[lp.Name].Kitchen.Areas:GetChildren()) do
    if(string.find(v.Name,"Stove") and v.Owned.Value == true) then
      local args = {
          [1] = "CookFood",
          [2] = {
              [1] = "Waffles",
              [2] = v
          }
      }
      game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
    end
  end

end)

main:Toggle2("Auto Sell",function()
  tp(CFrame.new(game:GetService("Workspace").Map.Collect.Position + Vector3.new(0,3,0)))
end)

main:Toggle2("Auto click cooking target",function()
  local args = {
      [1] = "TargetClick",
      [2] = {}
  }
  game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
end)
main:Toggle2("Auto Buy Stoves",function()
  for i,v in ipairs(game:GetService("Workspace").Players[lp.Name].Kitchen.Areas:GetChildren()) do
    if(v.Owned.Value == false) then
      local args = {
          [1] = "BuyKitchen",
          [2] = {
              [1] = (string.find(v.Name,"Stove") and "Stove") or "Counter",
              [2] = tonumber(string.gsub(string.gsub(v.Name,"Stove",""),"Counter",""))
          }
      }
      print(v.Name,i)
      game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
      wait()
    end
  end
end)
main:Toggle2("Auto Rebirth",function()
  game:GetService("ReplicatedStorage").RemoteEvent:FireServer("Rebirth",{})
  wait(10)
end)

main:Toggle2("Auto Buy Spatulas",function()
  return print("there is no such thing as auto buy spatulas ffs")
  -- local current = lp.PlayerGui.ToolBar.Bar.Slot1.Item.Value
  --
  -- local args = {
  --     [1] = "buyFromShop",
  --     [2] = {
  --         [1] = "Cobalt Spatula",
  --         [2] = "Spatulas"
  --     }
  -- }
  --
  -- game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))

end)

--[[

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "BuyKitchen",
    [2] = {
        [1] = "Counter",
        [2] = 2
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "BuyKitchen",
    [2] = {
        [1] = "Stove",
        [2] = 2
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))


]]--



--[[
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "EquipTool",
    [2] = {
        [1] = true,
        [2] = "Cobalt Spatula"
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))




]]
