library = library or _G.library or loadstring(game:HttpGet("http://zerotwohub.tk/uilibtest"))()
local window = library:CreateWindow("ZeroTwo Hub")
local main = window:CreateFolder("Main")

local lp = game.Players.LocalPlayer

-- Script generated by SimpleSpy - credits to exx#9394

main:Toggle2("Auto Upgrade Luck1",function()
  game:GetService("ReplicatedStorage").RemoteFunctions.BasicUpgrade:InvokeServer("BetterLuck")
  wait(1)
end)

main:Toggle2("Auto Prestige",function()
  game:GetService("ReplicatedStorage").RemoteFunctions.Prestige:InvokeServer()
  wait(5)
end)
