library = library or _G.library or loadstring(game:HttpGet("http://zerotwohub.tk/uilibtest.lua"))()
local window = library:CreateWindow("ZeroTwo Hub")
local main = window:CreateFolder("Main")

local lp = game.Players.LocalPlayer

function mag(part)
  if(lp.Character and lp.Character:FindFirstChild("HumanoidRootPart") and part:IsA("BasePart")) then
    return (lp.Character.HumanoidRootPart.Position - part.Position).Magnitude
  else
    return 0
  end
end

local pos = Vector3.new(0,0,0)

main:Toggle2("Auto Pickup",function()
  -- local args = {
  --     [1] = {
  --         [1] = "PickupShoe", --key / what to do
  --         [2] = "Starter", --zone
  --         [3] = Vector3.new(470.00857543945, 1, -36.555114746094), --shoeposition
  --         [4] = "Flip Flops" --shoename
  --     }
  -- }

  game:GetService("ReplicatedStorage").Events.Collect:FireServer({"PickupShoe","Starter",nil,"Pumpkin Shoes"})

end)

main:Toggle2("Auto Sell",function()
  top,topdis = nil,100
  for i,v in pairs(workspace.SellPlaces:GetChildren()) do
    if(mag(v) < topdis) then
      topdis = mag(v)
      top = v
    end
  end
  if(top) then
    game:GetService("ReplicatedStorage").Events.Click:FireServer({"Screen",top})
  end
end)

main:Toggle2("Auto Rebirth",function()
game:GetService("ReplicatedStorage").Events.Buy:FireServer({"Rebirth"})
wait(5)

end)

lp.PlayerGui.Main.ChildAdded:Connect(function(child)
  if(child.Name == "CashIncreased" or child.Name=="LacesIncreased") then
    child.Visible = false
  end
end)

main:Button("Buy & TP to Golden",function()
  -- Script generated by SimpleSpy - credits to exx#9394

  local args = {
      [1] = {
          [1] = "AreaBuy",
          [2] = "Golden"
      }
  }

  game:GetService("ReplicatedStorage").Events.Buy:FireServer(unpack(args))
  game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = workspace.SellPlaces.Golden.CFrame + Vector3.new(0,5,0)
end)

main:Button("Buy & TP to Japan",function()
  -- Script generated by SimpleSpy - credits to exx#9394

  local args = {
      [1] = {
          [1] = "AreaBuy",
          [2] = "Japan"
      }
  }

  game:GetService("ReplicatedStorage").Events.Buy:FireServer(unpack(args))
  game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = workspace.SellPlaces.Japan.CFrame + Vector3.new(0,5,0)
end)
